function interop_matlab(pyStore, mlStore)
%INTEROP_MATLAB Step 2: verify the python-written store, then write the
%   mirror store for python to verify.

cases = interop_case_list();

% ---- verify python-written store -------------------------------------
root = zarr.open(pyStore);
assert(root.attrs{"title"} == "interop" && root.attrs{"answer"} == 42, 'root attrs');
sub = root.item("sub");
assert(sub.attrs{"depth"} == 1, 'sub attrs');

% Reserved names of the hdmf-zarr Zarr v3 convention. Every one begins with
% an underscore, so none can be held in a struct; they are the reason
% attributes are exposed as a dictionary.
reserved = sub.attrs;
assert(reserved{"_DTYPE"} == "object_reference", '_DTYPE');
assert(isequal(reserved{"_REFERENCE_FIELDS"}, {"electrode"}), '_REFERENCE_FIELDS is a list');
assert(reserved{"_LINKS"}{1}{"path"} == "/general/devices/probe", '_LINKS entry');
assert(reserved{"_REF_ATTR"}{"_REFERENCE"}{"path"} == "/general/electrodes", 'nested _REFERENCE');

for i = 1:numel(cases)
    c = cases{i};
    z = zarr.open(pyStore, Path=c.name);
    expected = interop_pattern(c.shape, c.dtype);
    if ~isempty(c.partial)
        % Only a corner region was written; the rest must be fill.
        full = repmat(z.meta.fillValue, zarr.internal.mshape(c.shape));
        subs = arrayfun(@(p) 1:p, c.partial, 'UniformOutput', false);
        if isscalar(subs), subs{end + 1} = 1; end
        full(subs{:}) = expected(subs{:});
        expected = full;
    end
    if isempty(c.shape)
        actual = z();
    else
        actual = z.read();
    end
    assert(isequaln(actual, expected), 'read mismatch: %s', c.name);
    assert(isequal(class(actual), class(expected)), 'class mismatch: %s', c.name);
end

named = zarr.open(pyStore, Path="sub/named");
assert(isequaln(named.read(), interop_pattern([4 6], "float64")), 'named data');
assert(isequal(named.dimensionNames, ["y" "x"]), 'dimension_names');
assert(named.attrs.units == "mm" && named.attrs.scale == 1.5, 'array attrs');
fprintf('MATLAB verified %d python-written arrays\n', numel(cases) + 1);

% ---- write the mirror store for python to verify ----------------------
zarr.create_group(mlStore, Attributes=struct('title', 'interop', 'answer', 42));
g = zarr.open(mlStore);
subOut = g.createGroup("sub");
subOut.setAttr("depth", 1);
% Hand the reserved names straight back, so python sees exactly what it wrote.
for name = ["_DTYPE", "_REFERENCE_FIELDS", "_LINKS", "_REF_ATTR"]
    subOut.setAttr(name, reserved{name});
end

nWritten = 0;
for i = 1:numel(cases)
    c = cases{i};
    if c.writeSkip
        continue
    end
    extra = {};
    if ~isempty(c.shards)
        extra = {'ShardShape', c.shards, 'IndexLocation', c.indexLocation};
    end
    if c.v2keys
        extra = [extra, {'ChunkKeyEncoding', "v2"}];
    end
    z = zarr.create(mlStore, c.shape, c.dtype, 'Path', c.name, ...
        'ChunkShape', c.chunks, 'Codecs', c.codecs, 'FillValue', c.fill, extra{:});
    data = interop_pattern(c.shape, c.dtype);
    if ~isempty(c.partial)
        subs = arrayfun(@(p) 1:p, c.partial, 'UniformOutput', false);
        if isscalar(subs), subs{end + 1} = 1; end
        z.write(data(subs{:}), ones(1, numel(c.shape)));
    else
        z.write(data);
    end
    nWritten = nWritten + 1;
end

named = zarr.create(mlStore, [4 6], "float64", Path="sub/named", ChunkShape=[2 3], ...
    DimensionNames=["y" "x"], Attributes=struct('units', 'mm', 'scale', 1.5));
named.write(interop_pattern([4 6], "float64"));
fprintf('MATLAB wrote %d arrays\n', nWritten + 1);
end

function cases = interop_case_list()
%Mirror of tools/interop_cases.py CASES. writeSkip marks read-only cases
%(v2keys: zarr.create does not yet expose chunk key encoding).
gz5 = {zarr.codecs.GzipCodec(5)};
cases = { ...
    cs("f64_gzip", "float64", [10 13], [4 5], gz5, 0), ...
    cs("i32_crc", "int32", [5 4 3], [2 2 2], {zarr.codecs.GzipCodec(1), zarr.codecs.Crc32cCodec()}, 0), ...
    cs("f32_be", "float32", 8, 3, {zarr.codecs.BytesCodec("big")}, 0), ...
    cs("f64_transpose", "float64", [6 8], [3 4], {zarr.codecs.TransposeCodec([1 0])}, 0), ...
    cs("f16", "float16", 11, 4, gz5, 0), ...
    cs("c128", "complex128", [4 5], [2 3], gz5, 0), ...
    cs("c64", "complex64", 6, 4, {}, 0), ...
    cs("bool", "bool", [7 3], [4 2], {}, false), ...
    cs("u64", "uint64", 6, 4, {}, uint64(2)^60, 'partial', 3), ...
    cs("i64", "int64", 5, 2, {}, 0), ...
    cs("u8", "uint8", [9 2], [4 2], {}, 0), ...
    cs("i8", "int8", 9, 5, {}, 0), ...
    cs("u16", "uint16", 7, 3, {}, 0), ...
    cs("i16", "int16", 7, 3, {}, 0), ...
    cs("u32", "uint32", 7, 3, {}, 0), ...
    cs("f32", "float32", [3 4 2 2], [2 2 2 2], gz5, 0), ...
    cs("nanfill", "float64", [6 6], [3 3], {}, NaN, 'partial', [3 3]), ...
    cs("scalar", "float64", [], [], {}, 0), ...
    cs("v2keys", "float64", [5 5], [2 2], {}, 0, 'v2keys', true), ...
    cs("shard2d", "float64", [12 10], [3 5], gz5, 0, 'shards', [6 10]), ...
    cs("shard_start", "int32", [8 8], [2 2], {}, 0, 'shards', [4 8], 'indexLocation', "start"), ...
    cs("shard_fill", "float64", [8 8], [2 2], {}, NaN, 'shards', [4 4], 'partial', [2 2]), ...
    cs("shard3d", "int16", [6 4 4], [3 2 2], {zarr.codecs.GzipCodec(1), zarr.codecs.Crc32cCodec()}, 0, 'shards', [6 4 4]), ...
    cs("zstd_default", "float64", [10 8], [4 3], {zarr.codecs.ZstdCodec()}, 0), ...
    cs("zstd_hi_ck", "int32", 20, 7, {zarr.codecs.ZstdCodec(19, true)}, 0), ...
    cs("blosc_lz4_shuf", "float32", [9 7], [4 4], {zarr.codecs.BloscCodec(cname="lz4", clevel=5, shuffle="shuffle")}, 0), ...
    cs("blosc_zstd_bit", "int16", 12, 5, {zarr.codecs.BloscCodec(cname="zstd", clevel=3, shuffle="bitshuffle")}, 0), ...
    cs("blosc_blosclz_noshuf", "uint8", [6 6], [3 3], {zarr.codecs.BloscCodec(cname="blosclz", clevel=9, shuffle="noshuffle")}, 0), ...
    cs("shard_zstd", "float64", [8 8], [2 4], {zarr.codecs.ZstdCodec()}, 0, 'shards', [4 8]), ...
    cs("defaults", "float64", [7 5], [3 3], {zarr.codecs.ZstdCodec()}, 0), ...
    cs("str2d", "string", [5 4], [2 3], gz5, ""), ...
    cs("str_shard", "string", 6, 2, {}, "", 'shards', 6), ...
    cs("vbytes", "bytes", 7, 3, {}, uint8.empty(1, 0)), ...
    cs("dt_ns", "datetime64[ns]", 6, 3, {}, intmin('int64')), ...
    cs("td_ms", "timedelta64[ms]", 5, 2, gz5, intmin('int64')), ...
    cs("dt_fill", "datetime64[s]", 4, 2, {}, intmin('int64'), 'partial', 2), ...
    cs("blosc_lz4hc_shuf", "float64", [8 6], [3 3], {zarr.codecs.BloscCodec(cname="lz4hc", clevel=5, shuffle="shuffle")}, 0), ...
    cs("blosc_zlib_shuf", "int32", 10, 4, {zarr.codecs.BloscCodec(cname="zlib", clevel=5, shuffle="shuffle")}, 0), ...
    cs("gzip9", "float32", [6 6], [3 3], {zarr.codecs.GzipCodec(9)}, 0), ...
    cs("shard_nested", "float64", [8 8], [4 4], {zarr.codecs.ShardingCodec([2 2])}, 0, 'shards', [8 8]), ...
    cs("zlib5", "float64", [8 6], [4 3], {zarr.codecs.ZlibCodec(5)}, 0), ...
    cs("shuffle_zlib", "int32", 10, 4, {zarr.codecs.ShuffleCodec(4), zarr.codecs.ZlibCodec(1)}, 0), ...
    };
end

function c = cs(name, dtype, shape, chunks, codecs, fill, varargin)
c = struct('name', name, 'dtype', dtype, 'shape', shape, ...
    'chunks', chunks, 'codecs', {codecs}, 'fill', fill, ...
    'partial', [], 'writeSkip', false, 'shards', [], ...
    'indexLocation', "end", 'v2keys', false);
for i = 1:2:numel(varargin)
    c.(varargin{i}) = varargin{i + 1};
end
end
